### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by anaesco** [NVIDIA/cuda-repo-management#3]
Hi there, I am currently running a sequencing program called Master of Pores, and I am using the NVIDIA Docker/Cuda Container process to be able to run my pipeline using the GPU. However, I keep running to the error below and I was wondering if anyone could help me decipher what it is trying to say and/or if it is related to a failure in setting the development environment for CUDA...  (i am a student in bioinformatics! so my R knowledge is still pretty novel) Thanks in advance! 
Original command line: 

Command executed:
nextflow run mop_preprocess.nf -with-docker > test.txt

  export LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs"

  guppy_basecaller -x "cuda:0"         --fast5_out --flowcell FLO-MIN106 --kit SQK-RNA002  -i ./         --save_path ./wt---1_out         --gpu_runners_per_device 1         --cpu_threads_per_caller 1 	    --num_callers  1
  cat wt---1_out/*.fastq >> wt---1.fastq
  rm wt---1_out/*.fastq
  gzip wt---1.fastq

**Comment by elezar** [comment]
Hi @anaesco. Please open an issue against either https://github.com/NVIDIA/libnvidia-container or https://github.com/NVIDIA/nvidia-container-toolkit and provide more information on your exact setup and the error message that you see.

@kmittman feel free to close this issue here.
